### PR TITLE
Show better error message when internal error occures.

### PR DESCRIPTION
**Pull request by onovy**

### CODE REVIEW

**Comment by gholt** [comment]
Folks were worried about what detail was returned to the client and that the server operator should check the logs for detail; did the correct detail not make it to the logs?

**Comment by onovy** [comment]
yes, backtrace and message is in log.

**Comment by gholt** [comment]
Okay, I'll have to reject this one for now, sorry. I do remember that returning just any exception message could result in leaking more info than desired to the client in some cases (to be honest I don't remember any specific example though). If it's pretty important to you, I could certainly see it as an option if said option was off by default. Thanks a bunch for your work on Swauth!

**Comment by onovy** [comment]
i agree and thank you.

**Pull request closed without merging**
